---
title: "exogenous-variables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{exogenous-variables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r setup, include=FALSE}
# library(httptest2)
# start_vignette("nixtlar")

knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.width = 7, 
  fig.height = 4
)
```

```{r}
library(nixtlar)
```

## 1. Load data 

```{r}
# df = read.csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity-short-with-ex-vars.csv')
# head(df)
```

```{r}
# future_ex_vars_df = read.csv('https://raw.githubusercontent.com/Nixtla/transfer-learning-time-series/main/datasets/electricity-short-future-ex-vars.csv')
# head(future_ex_vars_df)
```

## 2. Generte TimeGPT forecast 

```{r}
# timegpt_fcst_ex_vars_df = timegpt_forecast(df = df, h = 24, id_col = "unique_id", X_df = future_ex_vars_df, level = c(80, 90))
# head(timegpt_fcst_ex_vars_df)
```

## 3. Plot TimeGPT forecast 
```{r}
#timegpt_plot(df, h = 24, id_col = "unique_id", max_insample_length = 200)
```


```{r, include=FALSE}
#end_vignette()
```


